# Generated by Django 3.2.8 on 2021-12-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('small_message', models.CharField(max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, choices=[('Call', 'c'), ('Directly', 'd')], max_length=10)),
                ('timming', models.TimeField(auto_now_add=True)),
                ('When', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('event', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memberId', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('expiry', models.DateField()),
                ('joined', models.DateField()),
                ('image', models.ImageField(default='default/person.png', upload_to='')),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('hold', models.BooleanField(default=False)),
                ('hold_date', models.DateField(blank=True, null=True)),
                ('hold_reason', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, choices=[('danger', 'danger'), ('warning', 'warning'), ('success', 'success'), ('info', 'info'), ('secondary', 'secondary'), ('', '')], default='', max_length=30)),
                ('color_message', models.CharField(blank=True, default=' ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('absentees', models.ManyToManyField(blank=True, related_name='_administrator_attendance_absentees_+', to='administrator.Member')),
                ('members', models.ManyToManyField(blank=True, related_name='_administrator_attendance_members_+', to='administrator.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Absentees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('days_count', models.IntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.member')),
            ],
        ),
    ]
